/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
#include <stdint.h>
// RCC (Clock Control) - Base commune pour activer les horloges
#define RCC_BASE      0x40021000
#define RCC_APB2ENR   (*(volatile uint32_t*)(RCC_BASE + 0x18)) // Pour GPIOC
#define RCC_APB1ENR   (*(volatile uint32_t*)(RCC_BASE + 0x1C)) // Pour TIM2

// GPIO (Exemple LED sur PC13)
#define GPIOC_BASE    0x40011000
#define GPIOC_CRH     (*(volatile uint32_t*)(GPIOC_BASE + 0x04))
#define GPIOC_ODR     (*(volatile uint32_t*)(GPIOC_BASE + 0x0C))

// TIMER 2
#define TIM2_BASE     0x40000000
#define TIM2_CR1      (*(volatile uint32_t*)(TIM2_BASE + 0x00))//Control Register 1
#define TIM2_DIER     (*(volatile uint32_t*)(TIM2_BASE + 0x0C))//DMA/Interrupt Enable Register
#define TIM2_SR       (*(volatile uint32_t*)(TIM2_BASE + 0x10))//Status Register
#define TIM2_PSC      (*(volatile uint32_t*)(TIM2_BASE + 0x28))//Prescaler Register: Le diviseur de fréquence
#define TIM2_ARR      (*(volatile uint32_t*)(TIM2_BASE + 0x2C))//Auto-Reload Register :Le registre de rechargement automatique (la "limite")

// NVIC (Cortex-M3/M4 Interrupt Controller)
#define NVIC_ISER0    (*(volatile uint32_t*)(0xE000E100)) // Interrupt Set-Enable Register

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

void TIM2_IRQHandler(void) {
    // 1. Vérifier si c'est bien l'interruption de mise à jour (Update)(c 'est a dire il ya un overflow on a atteint la valeur 1s )
    if (TIM2_SR & (1 << 0)) {
        // 2. IMPORTANT : Effacer le flag d'interruption (UIF = 0)
        TIM2_SR &= ~(1 << 0);

        // 3. Faire basculer (Toggle) la LED sur PC13
        GPIOC_ODR ^= (1 << 13);
    }
}

int main(void)
{
    // 1. Activer les horloges
    RCC_APB2ENR |= (1 << 4);  // Activer GPIOC
    RCC_APB1ENR |= (1 << 0);  // Activer TIM2
    // 2. Configurer PC13 en sortie (LED sur BluePill)
    GPIOC_CRH &= ~(0xF << 20); // Reset PC13
    GPIOC_CRH |= (0x2 << 20);  // Mode Output 2MHz, Push-Pull
    //GPIOC_ODR |=(1<<13);

	TIM2_PSC =7999;
	TIM2_ARR=999;
	TIM2_CR1 |= (1 << 0);      // CEN = 1(mode compteur) Démarrer le Timer
	TIM2_DIER |=(1<<0);		   //mettre  Le bit UIE (Update Interrupt Enable)en 1( Il permet d'activer spécifiquement quels événements déclenchent une interruption CPU)

	//permet au Timer d'envoyer un signal d'interruption au processeur
	//chaque fois que le compteur atteint la valeur définie dans le registre ARR
    // Activer l'interruption au niveau du Cœur (NVIC)
    // TIM2 est l'interruption 28. On active le bit 28 de ISER0
    NVIC_ISER0 |= (1 << 28);

    while(1){

    }


}
