/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#define RCC_BASE 0x40021000
#define RCC_APB2ENR (*(uint32_t*)(RCC_BASE + 0x18))

#define GPIOA_BASE 0x40010800
#define GPIOA_CRL	(*(uint32_t*)(GPIOA_BASE + 0x00))
#define GPIOA_IDR	(*(uint32_t*)(GPIOA_BASE + 0x08))
#define GPIOA_ODR	(*(uint32_t*)(GPIOA_BASE +  0x0C))


uint32_t portValue;
#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	RCC_APB2ENR |=(1<<2);//GPIOA horloge activé
	GPIOA_CRL &=~(0xF<<4);// nettoyage des bits
	GPIOA_CRL |=(0x8<<4);//PA1 en input pull-up /pyll -down
    // choisir pull-down sur PA1
    GPIOA_ODR &= ~(1<<1);//ou bien (0<<1)

	GPIOA_CRL &=~(0xF<<8);// nettoyage des bits
	GPIOA_CRL |=(0x6<<8); //PA2 en output Open-drain
	//pour lire le bit 1, il faut un masque
	portValue=(GPIOA_IDR << 1) & 1;//lire port 1
	if(portValue ==1){
		GPIOA_ODR |=(1<<2);  //allumer led dans PA2
	}

    /* Loop forever */
	for(;;);
}
