/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f103xb.h"
uint16_t value;

void ADC1_Init(){
	RCC->APB2ENR |=RCC_APB2ENR_ADC1EN; //activer l'horloge de APB2
	ADC1->CR2 |=ADC_CR2_ADON; //allumer l'ADC
    // Attendre un peu que l'ADC se stabilise (optionnel mais conseillé)
    for(int i=0; i<1000; i++);
	ADC1->CR2 |=ADC_CR2_ADON;
	ADC1->CR2 |=ADC_CR2_CONT;//MODE continue
	ADC1->SQR3 =0;//selectionne la broche 0 du port A (c'est par défaut le constructeur de carte selectioone le canal 0 a PA0 ,voir datasheet)
}
void GPIOA_Init(){
	RCC->APB2ENR |=RCC_APB2ENR_IOPAEN;// Horloge GPIOA
	GPIOA->CRL &=~(0xF);//input analog mode (0000)
}
#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	GPIOA_Init();
	ADC1_Init();
	 // Lancer la première conversion
	ADC1->CR2 |=ADC_CR2_SWSTART;
	while(1){
		while(!(ADC1->SR & ADC_SR_EOC)); //ici on attend tant que EOC =0 conversion pas terminé (on bloque dans while)
		//une fois est terminé ,on passe a lire la valeur (0->4095) (cela remet EOC à 0 automatiquement)
		value=ADC1->DR;
	}
}
