/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f1xx.h"// Fichier spécifique au STM32F103 Medium Density (C8T6)


void GPIO_Init_F1(void) {
    // 1. Activer les horloges GPIOA, TIM2 et TIM3
    RCC->APB2ENR |= RCC_APB2ENR_IOPAEN;
    RCC->APB1ENR |= RCC_APB1ENR_TIM2EN | RCC_APB1ENR_TIM3EN;

    // 2. PA0 (TIM2_CH1) : Entrée flottante (Mode Input = 00, Conf = 01 -> 0x4)
    GPIOA->CRL &= ~(0xF << (0 * 4)); // Reset PA0
    GPIOA->CRL |=  (0x4 << (0 * 4)); // Input Floating

    // 3. PA6 (TIM3_CH1) : Sortie Alternée Push-Pull (Mode 50MHz = 11, Conf AF = 10 -> 0xB)
    GPIOA->CRL &= ~(0xF << (6 * 4)); // Reset PA6
    GPIOA->CRL |=  (0xB << (6 * 4)); // Alternate Function Push-Pull
}
void TIM3_Generator_Init(void) {
    // Fréquence = 8MHz / (PSC+1) / (ARR+1) = 8MHz / 8 / 1000 = 1kHz
    TIM3->PSC = 7;
    TIM3->ARR = 999;

    // Configuration du Mode PWM 1 sur le Channel 1
    TIM3->CCMR1 |= (0x6 << TIM_CCMR1_OC1M_Pos); // PWM mode 1
    TIM3->CCMR1 |= TIM_CCMR1_OC1PE;            // Preload enable

    // Duty cycle : 25% de 1000 = 250
    TIM3->CCR1 = 250;

    // Activation de la sortie et du compteur
    TIM3->CCER |= TIM_CCER_CC1E;
    TIM3->CR1 |= TIM_CR1_CEN;
}
void TIM2_Measure_Init(void) {
    // Résolution de 1µs (8MHz / (7+1))
    TIM2->PSC = 7;
    TIM2->ARR = 0xFFFF;

    // Configuration Capture Compare :
    // TI1 est la source. IC1 capture direct, IC2 capture indirect
    TIM2->CCMR1 |= (0x1 << TIM_CCMR1_CC1S_Pos); // IC1 mappé sur TI1
    TIM2->CCMR1 |= (0x2 << TIM_CCMR1_CC2S_Pos); // IC2 mappé sur TI1

    // Polarité : IC1 = Montant (Période), IC2 = Descendant (Temps haut)
    TIM2->CCER &= ~TIM_CCER_CC1P;
    TIM2->CCER |=  TIM_CCER_CC2P;

    // Mode Esclave : Trigger sur TI1FP1 (TS=101) et Reset du compteur (SMS=100)
    TIM2->SMCR |= (0x5 << TIM_SMCR_TS_Pos);
    TIM2->SMCR |= (0x4 << TIM_SMCR_SMS_Pos);

    // Activer les captures et le Timer
    TIM2->CCER |= (TIM_CCER_CC1E | TIM_CCER_CC2E);
    TIM2->CR1 |= TIM_CR1_CEN;
}

volatile uint32_t periode_us = 0;
volatile uint32_t temps_haut_us = 0;
volatile uint32_t rapport_cyclique = 0;

int main(void)
{
    GPIO_Init_F1();
    TIM3_Generator_Init();
    TIM2_Measure_Init();



    while (1) {
        // CCR1 contient le nombre de ticks entre deux fronts montants
        periode_us = TIM2->CCR1;

        // CCR2 contient le nombre de ticks entre le front montant et descendant
        temps_haut_us = TIM2->CCR2;

        if (periode_us > 0) {
            rapport_cyclique = (temps_haut_us * 100 / periode_us) ;
        }

        // Petite pause pour stabiliser la lecture en debug
        for(volatile int i=0; i<100; i++);
    }
}
