/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

//int *address = (int*) 0x18;

#define RCC_BASE       0x40021000     // Suppression de l'espace
#define RCC_APB2ENR    (*( uint32_t*)(RCC_BASE + 0x18))
//
#define GPIOC_BASE     0x40011000     // Suppression de l'espace
#define GPIOC_CRH      (*(uint32_t*)(GPIOC_BASE + 0x04))
#define GPIOC_ODR      (*(uint32_t*)(GPIOC_BASE + 0x0C))
#define GPIOC_BSRR     (*(uint32_t*)(GPIOC_BASE + 0x10))
//ya nesta3mel ODR ya BSRR ,ODR tnejem ta9ra meno state w tbedel ( can be accessed in Word mode only)
//BSRR registre m9asam chtar pour le set chtar pour le reset
#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

// Correction de la fonction delay
void delay(uint32_t x) {
    for(uint32_t i = 0; i < x; i++) {
        __asm__("nop");  // Ajout d'une instruction pour éviter l'optimisation
    }
}
int main(void)
{
	RCC_APB2ENR |=(1<<4);//active de l'horloge du port GPIOC
	GPIOC_CRH &=~(0xF<<20);//nettoyage des bits
	GPIOC_CRH |=(0x2<<20);//configuration output push-pull avec max speed 2MHZ

    /* Loop forever */
	/*//solution1 avec registre ODR
	while(1){
		GPIOC_ODR^=(1<<13);
		delay(1000000);
	}
	*/
	//solution2 avec registre BSRR
	while(1){
		GPIOC_BSRR =(1<<13);
		delay(500000);
		GPIOC_BSRR =(1<<(13+16));
		delay(500000);
	}

}
