/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#include "stm32f1xx.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

void clock_config(){
	//active l'horloge de USART1
	RCC->APB2ENR |=RCC_APB2ENR_USART1EN ;
	//active l'horloge du port A car (PA9 = TX, PA10 = RX)
	RCC->APB2ENR |=RCC_APB2ENR_IOPAEN ;
	// Activer l'horloge AFIO (pour la remapping si nécessaire)
	RCC->APB2ENR |= RCC_APB2ENR_AFIOEN;
	RCC->APB2ENR |= RCC_APB2ENR_IOPCEN;
}
void pin_config(){
	// PA9 (TX) : Alternate Function Push-Pull, Output 50MHz
	GPIOA->CRH &= ~(0xF << 4);   // Reset bits pour PA9
	GPIOA->CRH |= (0xB << 4);    // 1011: AF Push-Pull, 50MHz
	// PA10 (RX) : Input Floating
	GPIOA->CRH &= ~(0xF << 8);    // Reset bits pour PA10
	GPIOA->CRH |= (0x4 << 8);     // 0100: Input Floating
	// Configuration LED sur PC13 (typique sur Blue Pill)
	GPIOC->CRH &= ~(0xF << 20);
	GPIOC->CRH |= (0x3 << 20);  // Output Push-Pull 50MHz
}
void UART1_Init(uint32_t baudrate){
    // Calcul du baudrate (sysclk = 72MHz typiquement)
    // BRR = sysclk / baudrate
    USART1->BRR = 8000000 / baudrate;
    USART1->CR1 |=USART_CR1_TE | USART_CR1_RE | USART_CR1_UE;
}
//Envoie d'un caractére
void UART1_SendChar(char c) {
    while (!(USART1->SR & USART_SR_TXE));  // Attendre buffer vide cette condition c'est a dire il y a en core data dans le shift registre
    USART1->DR = c;
}

// Réception d'un caractère
char UART1_ReceiveChar(void) {
    while (!(USART1->SR & USART_SR_RXNE));   // Attendre données
    return USART1->DR;
}

// Envoi d'une chaîne
void UART1_SendString(const char* str) {
    while (*str) {
        UART1_SendChar(*str++);
    }
}


void LED_Toggle(void) {
    GPIOC->ODR ^= (1 << 13);
	}
int main(void)
{
	clock_config();
	pin_config();
    UART1_Init(9600);
    while(1) {
        UART1_SendString("Test\r\n");
        LED_Toggle();  // Clignote à chaque envoi
        for(volatile int i=0; i<1000000; i++); // Delay
    }
}
