/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
// --- ADRESSES DE BASE ---
#define RCC_BASE 0x40021000
#define GPIOA_BASE 0x40010800
#define TIM2_BASE 0x40000000
// --- REGISTRES RCC (Horloges) ---
#define RCC_APB1ENR (*(uint32_t*)(RCC_BASE + 0x1C))//clock du timer 2
#define RCC_APB2ENR (*(uint32_t*)(RCC_BASE + 0x18))//clock du port A

// --- REGISTRES GPIOA ---
#define GPIOA_CRL (*(uint32_t*)(GPIOA_BASE + 0x00)) //pour le configurer en input ou output
#define GPIOA_ODR (*(uint32_t*)(GPIOA_BASE + 0x0C))//pour modifier son état HIGH ,LOW

// --- REGISTRES TIMER 2 ---
#define TIM2_CR1      (*(volatile uint32_t*)(TIM2_BASE + 0x00)) // Controle (Start/Stop
#define TIM2_PSC      (*(volatile uint32_t*)(TIM2_BASE + 0x28)) // Prescaler (Vitesse)
#define TIM2_ARR      (*(volatile uint32_t*)(TIM2_BASE + 0x2C)) // Auto-reload (Période)
#define TIM2_CCMR1 (*(uint32_t*)(TIM2_BASE + 0x18))//Pour le configurer en entré ou sortie
#define TIM2_CCER     (*(volatile uint32_t*)(TIM2_BASE + 0x20))// Pour controler l'activation
#define TIM2_CCR1 (*(uint32_t*)(TIM2_BASE +0x34))     // Duty Cycle (Luminosité)



void delay(uint32_t count) {
    for(volatile uint32_t i = 0; i < count; i++);
}

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
    // 1. Activer les horloges
    RCC_APB2ENR |= (1 << 2);  // Enable GPIOA
    RCC_APB1ENR |= (1 << 0);  // Enable TIM2
    // 2. Configurer PA8 en "Alternate Function Push-Pull" (Mode PWM)
    // On nettoie les 4 premiers bits et on met 0xB (1011b) : AF Output 50MHz
    GPIOA_CRL &= ~(0xF << 0);
    GPIOA_CRL |=  (0xB << 0);
    // 3. Configurer le Timer 2
    TIM2_PSC = 7999;           // Divise l'horloge (8MHz / 7999 = 1000Hz)
    TIM2_ARR = 3999;          // 1000Hz / 4000 = 0.2 5Hz (Fréquence du PWM)-> T=4s  (c'est la limite du compteur)
    // Configurer le mode PWM 1 sur le Canal 1 (OC1M = 110)
    TIM2_CCMR1 |= (0x6 << 4);
    // Activer la sortie physique sur la PIN (CC1E = 1)
    TIM2_CCER |= (1 << 0);
    // Démarrer le Timer (CEN = 1)
    TIM2_CR1 |= (1 << 0);
    //rapport cyclique égal a 3 s
    TIM2_CCR1 = 2000;
/*
 * Le Timer compte de 0 à 2999 : La condition CNT < CCR1 est vraie → Sortie HIGH
 * CNT: C'est le compteur interne du Timer. Imagine un petit curseur qui avance tout seul à l'intérieur de la puce
 * ARR : C'est la ligne d'arrivée (le mur).
 *CCR1 : C'est la ligne où on change d'état (le drapeau).
 *CNT : C'est le coureur qui court sans s'arrêter entre 0 et ARR.
 * */
    //while(1){
      /*
    	// Effet FADE IN
        for(int i = 0; i <= 1000; i++) {
            TIM2_CCR1 = i;
            delay(500);
        }
        // Effet FADE OUT
        for(int i = 1000; i >= 0; i--) {
            TIM2_CCR1 = i;
            delay(500);
        }
    }
    */

}
